### ISSUE TITLE
Pages other than index.js do not render

### ISSUE THREAD

**Issue by stahlmanDesign** [digitalocean/sample-nextjs#6]
I deployed my site using Vercel with no problems, and was hoping to use DO but can't get the same project to work. It won't render routes other than index.js

I cloned this sample repo and deployed. Worked fine. But then I added test.js in the /pages folder and it does not render either.

**Comment by stahlmanDesign** [comment]
I think my issue is exactly the same as https://github.com/digitalocean/sample-nextjs/issues/2

**Comment by stahlmanDesign** [comment]
The solution adding `trailingSlash: true` causes the custom 404 page to be treated the same way as the routes, but this special page needs to remain 404.html. So the fix breaks the custom 404 and the default 404 page is shown.

https://github.com/vercel/next.js/issues/16528
https://github.com/vercel/next.js/issues/16528#issuecomment-720228757

**Comment by stahlmanDesign** [comment]
All of these issues show up only in prod, when deployed.

They are not present when you `npm run dev -- -p 3004` or `npm run build` and `npm start -- -p 3004` (viewing on port 3004)

**Comment by kamaln7** [comment]
👋🏼 @stahlmanDesign thanks for reporting this and following up with the updates. If the only problem with `trailingSlash: true` is that the 404 page is rendered as `/404/index.html` instead of `/404.html`, you can update your build command to address that.

For example, if your build command is `npm run build`, you can use `npm run build && mv out/404/index.html out/404.html && rm -r out/404`. The `rm -r out/404` is optional but it cleans up the empty `404` directory that is left after moving `index.html` out of it.

Let me know if that works!

**Comment by stahlmanDesign** [comment]
According to this example project, `out` should be `_static`. So I added your code to the build script in package.json and it works:
```
"scripts": {
    "dev": "next",
    "build": "next build && next export -o _static && mv _static/404/index.html _static/404.html && rm -r _static/404",
    "start": "node sammy.js; next start -H 0.0.0.0 -p ${PORT:-8080}"
  },
```
Thanks for that idea. I still wonder why I didn't have to do this when publishing to Vercel. They might doing additional checks behind the scenes since they manage NextJS

**Comment by kamaln7** [comment]
That's great! We'll add this to the [Next.js documentation page](https://www.digitalocean.com/docs/app-platform/languages-frameworks/next.js/).

This is needed because our CDN currently does not automatically fall back to checking if a file with the `.html` extension exists, so it doesn't know to map `/page` to `/page.html`. We're tracking this internally and are looking into ways to make the user experience better and allow more frameworks to work out of the box without config changes 🙂
